spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/store}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 50
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cache:
    type: redis
    redis:
      time-to-live: 1800000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "store_cache_"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 1000ms


global:
  search:
    sort-field: id
    limit: 30
    sort-direction: asc

customer:
  search:
    sort-field: name
    limit: 20
    sort-direction: asc